triggerTitansProject/force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

triggerTitansProject/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

triggerTitansProject/force-app/main/default/classes/JobApplicationHandler.cls
public with sharing class JobApplicationHandler {
    public static void handleAfterUpdate(Map<Id, Job_Application__c> oldMap, List<Job_Application__c> applications) {
        List<String> savedStatusSubjects = new List<String>{
                                                    'Check if the job description aligns with your interests and values',
                                                    'Review the highlighted skills to see if the role is a good fit',
                                                    'Research the company or role and mark your excitement level'
                                                };
        
        List<Job_Application__c> applicationsToUpdate = new List<Job_Application__c>();
        
        for(Job_Application__c application : applications) {
            if(application.Status__c != oldMap.get(application.Id).Status__c) {
                if(application.Status__c == 'Saved') {
                    JobApplicationTaskCreation.createTasks(application, savedStatusSubjects);
                }
            } else continue;
        }
    } 
}