force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <inlineHelpText>A date field to specify when to follow up on the application</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

triggerTitansProject/force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseOldApplications.cls
public class CloseOldApplications implements Database.Batchable<sObject> {
    private Date dateThreshold;

    public CloseOldApplications() {
        dateThreshold = Date.today().addDays(-30);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Status__c, Follow_Up_Date__c, Notes__c ' +
            'FROM Job_Application__c ' +
            'WHERE Status__c != \'Closed\' ' +
            'AND Status__c != \'Accepted\' ' +
            'AND Follow_Up_Date__c <= :dateThreshold'
        );
    }
    public void execute(Database.BatchableContext BC, List<Job_Application__c> scope) {
        for (Job_Application__c application : scope) {
            application.Status__c = 'Closed';
            application.Notes__c = 'Closed by automatic process 30 days after Follow-Up Date: ' + application.Follow_Up_Date__c.format() + '.';
        }
        try {
            update scope;
        } catch (Exception e) {
            System.debug(e);
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}